version: "3.8"
services:
  mongo:
    image: mongo:6
    volumes:
      - data:/data/db

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: test-key
      MONGO_URL: mongodb://mongo:27017/todo

volumes:
  data:

